version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_coupon_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coupon_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis_coupon_container
    restart: always
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: go_coupon_app
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: coupon_db
      DB_PORT: 3306
      RDB_HOST: redis
      RDB_PORT: 6379
    ports:
      - "8081:8081"
volumes:
  mysql_data: